org: alphajuliet
app: genpwd
service: genpwd-sls
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  httpApi:
    cors: true

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
  generate:
    handler: src/genpwd.generate
    events:
      - httpApi:
          path: /generate
          method: get
  generators:
    handler: src/genpwd.generators
    events:
      - httpApi:
          path: /generators
          method: get
